version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/trade/bk-bot
  - source: .
    destination: /home/ubuntu/trade/bk-bot-cstar
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: pm2/reload-pm2.sh
      timeout: 3600
      runas: ubuntu